development:
 adapter: postgresql
 encoding: unicode
 database: junk_dev
 host: localhost
 username: drew
 password: drew

test:
 adapter: postgresql
 encoding: unicode
 database: junk_test
 pool: 5
 host: localhost
 username: drew
 password: drew

production:
 adapter: postgresql
 encoding: unicode
 database: junk_dev
 pool: 5
 host: localhost
 username: drew
 password: drew